const actionNames = {
    SET_SELECTED_PARTICIPANT: "SET_SELECTED_PARTICIPANT",
    SET_PARTICIPANTS: "SET_PARTICIPANTS",
    SET_SELECTED_SLIDE: "SET_SELECTED_SLIDE"
};

export default actionNames;