const actionNames = {
    SET_SELECTED_PARTICIPANT: "SET_SELECTED_PARTICIPANT",
    SET_PARTICIPANTS: "SET_PARTICIPANTS",
    SET_SELECTED_SLIDE: "SET_SELECTED_SLIDE",
    SET_SELECTED_ACCORDION: "SET_SELECTED_ACCORDION",
    SET_SELECTED_METADATA: "SET_SELECTED_METADATA",
};

export default actionNames;